### ISSUE TITLE
Fails if installed via gems

### ISSUE THREAD

**Issue by gebner** [izuzak/github_issue_stats#12]
When I install `github_issue_stats` (on a fresh Ubuntu trusty image) as a gem it can't find `Octokit`:

```
root@07368e61a34e:/# gem install github_issue_stats
...
root@07368e61a34e:/# github_issue_stats
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- Octokit (LoadError)
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/github_issue_stats-0.4.0/lib/github_issue_stats.rb:2:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/github_issue_stats-0.4.0/bin/github_issue_stats:5:in `<top (required)>'
        from /usr/local/bin/github_issue_stats:23:in `load'
        from /usr/local/bin/github_issue_stats:23:in `<main>'
```

After replacing `Octokit` with the lowercase `octokit`, everything works fine.

**Comment by izuzak** [comment]
Thanks so much for the report! That works on OSX for me, but I should be testing on other OSes it seems. I'll publish a new version shorty.
